export const initialContent = {
  pt: {
    // Nav
    nav_about: 'Sobre Nós',
    nav_know_us: 'Conheça-nos',
    nav_products: 'Loja',
    nav_advertising: 'Anúncios',
    nav_downloads: 'Downloads',
    joinNow: 'Associe-se Já',
    
    // Products (still needed for labels like buyNow)
    buyNow: 'Comprar Agora',

    // Contact Form
    contact_form_title: 'Entre em Contato',
    contact_form_name: 'Seu Nome',
    contact_form_email: 'Seu E-mail',
    contact_form_message: 'Sua Mensagem',
    contact_form_submit: 'Enviar Mensagem',
    contact_form_success: 'Obrigado pelo seu contato! Retornaremos em breve.',
    'contact_form_sending': 'Enviando...',
    'contact_form_alert_demo': 'Em uma aplicação real, isso enviaria um email ou salvaria os dados em um servidor.',


    // Chatbot
    chatbot_greeting: 'Olá! 👋 Sou {chatbotName}. Como posso ajudar hoje?',
    chatbot_placeholder: 'Digite sua pergunta...',

    // Admin Panel
    admin_dashboard: 'Início',
    admin_pages: 'Páginas',
    admin_store: 'Loja',
    admin_offers: 'Ofertas',
    admin_carts: 'Carrinhos',
    admin_orders: 'Pedidos',
    admin_advertising: 'Anúncios',
    admin_downloads: 'Downloads',
    admin_theme: 'Tema',
    admin_settings: 'Configurações do Site',
    admin_ai_settings: 'Configurações de IA',
    admin_integrations: 'Integrações',
    admin_welcome: 'Bem-vindo ao Painel de Administração',
    admin_welcome_desc: 'Use a navegação à esquerda para gerenciar o conteúdo do seu site.',
    admin_downloads_title: 'Gerenciamento de Downloads',
    admin_downloads_plan: 'Páginas do Plano de Marketing',
    admin_downloads_catalog: 'Páginas do Catálogo de Produtos',
    admin_downloads_add_page: 'Adicionar Página',
    admin_pages_title: 'Construtor de Páginas',
    admin_pages_desc: 'Crie e gerencie o conteúdo das páginas do seu site.',
    admin_pages_add: 'Criar Nova Página',
    admin_pages_create_title: 'Criar Nova Página',
    'admin_page_editor_title': 'Editor de Página',
    'admin_page_meta_title': 'Configurações da Página',
    'admin_page_seo_title': 'Configurações de SEO',
    'admin_page_field_title': 'Título da Página',
    'admin_page_field_slug': 'URL Slug (ex: sobre-nos)',
    'admin_page_field_nav': 'Exibir na Navegação Principal',
    'admin_page_field_product': 'Produto Associado (Opcional)',
    'admin_page_field_product_none': 'Nenhum',
    'admin_page_containers_title': 'Contêineres de Conteúdo',
    'admin_page_containers_add': 'Adicionar Contêiner',
    'admin_container_select_type': 'Selecione o tipo de contêiner',
    'admin_container_type_text': 'Texto',
    'admin_container_type_image': 'Imagem',
    'admin_container_type_textImage': 'Texto + Imagem',
    'admin_container_type_columns': 'Colunas',
    'admin_container_type_contactForm': 'Formulário de Contato',
    'admin_container_type_video': 'Vídeo',
    'admin_container_type_hero': 'Seção Hero',
    'admin_container_type_about': 'Seção Sobre',
    'admin_container_type_differentiators': 'Seção Diferenciais',
    'admin_container_type_productsCarousel': 'Carrossel de Produtos',
    'admin_container_type_promotionsCarousel': 'Carrossel de Promoções',
    'admin_container_type_teamMembers': 'Membros da Equipe',
    'admin_container_type_downloadsList': 'Lista de Downloads',
    'admin_container_type_advertisingList': 'Lista de Anúncios',
    'admin_container_edit_title': 'Editar Contêiner',
    'admin_container_field_title': 'Título (Opcional)',
    'admin_container_field_subtitle': 'Subtítulo (Opcional)',
    'admin_container_field_content': 'Conteúdo do Texto',
    'admin_container_field_img_url': 'URL da Imagem',
    'admin_container_field_alt': 'Texto Alternativo da Imagem',
    'admin_container_field_layout': 'Layout',
    'admin_layout_img_left': 'Imagem à Esquerda',
    'admin_layout_img_right': 'Imagem à Direita',
    'admin_layout_img_top': 'Imagem Acima',
    'admin_layout_img_bottom': 'Imagem Abaixo',
    admin_advertising_title: 'Gerenciador de Anúncios',
    admin_advertising_desc: 'Crie e gerencie os anúncios e campanhas que aparecem no site.',
    admin_advertising_add: 'Criar Novo Anúncio',
    admin_ad_editor_title: 'Editor de Anúncio',
    admin_ad_field_title: 'Título do Anúncio',
    admin_ad_field_desc: 'Descrição',
    admin_ad_field_img_url: 'URL da Imagem do Anúncio',
    admin_ad_field_cta_text: 'Texto do Botão (CTA)',
    admin_ad_field_cta_link: 'Link do Botão (CTA)',
    admin_ad_field_active: 'Anúncio Ativo',
    admin_button_cancel: 'Cancelar',
    admin_button_create: 'Criar',
    admin_button_save: 'Salvar Alterações',
    'admin_button_save_short': 'Salvar',
    admin_button_delete: 'Excluir',
    admin_product_editor_title: 'Editor de Produto',
    admin_product_add_digital: '+ Adicionar Digital',
    admin_product_add_physical: '+ Adicionar Físico',
    'admin_store_management_title': 'Gerenciamento da Loja',
    'admin_store_management_desc': 'Adicione, edite e gerencie os produtos da sua loja.',
    admin_product_digital_products_title: 'Produtos Digitais',
    admin_product_physical_products_title: 'Produtos Físicos',
    admin_product_field_name: 'Nome',
    admin_product_field_category: 'Categoria',
    admin_product_field_description: 'Descrição',
    admin_product_field_price: 'Preço (BRL)',
    'admin_product_field_purchase_url': 'URL de Compra',
    'admin_product_tab_general': 'Gerais',
    'admin_product_tab_images': 'Imagens',
    'admin_product_tab_variants': 'Variações',
    'admin_product_tab_reviews': 'Avaliações',
    admin_ai_title: 'Configurações de Inteligência Artificial',
    admin_ai_desc: 'Gerencie o comportamento e a aparência do seu assistente de IA.',
    admin_chatbot_config_title: 'Configuração do Chatbot',
    admin_chatbot_name: 'Nome do Chatbot',
    admin_chatbot_icon: 'Ícone do Chatbot',
    admin_chatbot_prompt: 'Prompt do Sistema do Chatbot (Instruções)',
    admin_chatbot_prompt_desc: 'Instruções para a IA sobre como se comportar, seu tom e as informações que ela deve conhecer.',
    admin_integrations_title: 'Integrações de API',
    admin_integrations_desc: 'Configure chaves de API para serviços de terceiros.',
    admin_payment_gateways: 'Gateways de Pagamento',
    admin_shipping_integrations: 'Integrações de Envio',
    admin_key_mercado_pago: 'Chave do Mercado Pago',
    admin_key_adyen: 'Chave da Adyen',
    admin_key_stripe: 'Chave do Stripe',
    admin_key_pagseguro: 'Chave do PagSeguro',
    admin_key_stone: 'Chave da Stone',
    admin_key_asaas: 'Chave da Asaas',
    admin_key_melhor_envio: 'Chave do Melhor Envio',
    admin_api_keys_note_title: 'Nota Importante Sobre Chaves de API',
    admin_api_keys_note_desc: 'Para sua segurança, a chave de API do Gemini (o cérebro do nosso chatbot) é gerenciada em um ambiente seguro no servidor (variáveis de ambiente) e não pode ser editada aqui. As chaves abaixo são para integrações de pagamento e são salvas localmente no seu navegador.',
    admin_settings_social_title: 'Links de Redes Sociais',
    admin_settings_social_desc: 'Adicione, edite ou remova os links de redes sociais que aparecem no rodapé do site.',
    admin_settings_social_add: 'Adicionar Novo Link',
    admin_settings_social_platform: 'Plataforma (ex: facebook, x)',
    admin_settings_social_url: 'URL do Link',
    advertising_no_ads: 'Nenhum anúncio ativo no momento.',

    // Banners Tab
    'admin_banners_tab_label': 'Banners',
    'admin_banners_title': 'Gerenciamento de Banners',
    'admin_banners_side_banner': 'Banner Lateral',
    'admin_banners_background_banner': 'Banner de Fundo',
    'admin_banners_disabled_enabled': 'Desativado / Ativado',
    'admin_banners_image_url': 'URL da Imagem',
    'admin_banners_link_url': 'URL do Link',
    'admin_banners_position': 'Posição',
    'admin_banners_position_left': 'Esquerda',
    'admin_banners_position_right': 'Direita',
    'admin_banners_top_offset': 'Distância do Topo',
    'admin_banners_width': 'Largura',
    'admin_banners_opacity': 'Opacidade da Imagem',
    'admin_banners_opacity_hint': '(deixa mais claro ou escuro)',
    'admin_banners_save': 'Salvar Configurações dos Banners',

    // Admin Panel
    'admin_panel_minimize': 'Minimizar',
    'admin_panel_maximize': 'Maximizar',
    'admin_panel_restore': 'Restaurar',
    'admin_panel_close': 'Fechar Painel',
    'admin_panel_view_site': 'Ver Site',
    'admin_panel_logout': 'Sair',

    // Login Panel
    'admin_login_title': 'Login de Administrador',
    'admin_login_email': 'Email',
    'admin_login_password': 'Senha',
    'admin_login_remember': 'Lembrar-me',
    'admin_login_error': 'Email ou senha inválidos.',
    'admin_login_button': 'Entrar',
    'admin_login_close_aria': 'Fechar painel de login',
    
    // Theme Editor
    'theme_editor_title': 'Personalização do Tema',
    'theme_editor_reset': 'Redefinir para Padrão',
    'theme_editor_reset_confirm': 'Tem certeza que deseja redefinir todas as configurações de tema para o padrão? Suas alterações serão perdidas a menos que sejam salvas.',
    'theme_editor_saved_success': 'Tema salvo com sucesso!',
    'theme_editor_header_nav': 'Cabeçalho & Navegação',
    'theme_editor_mobile_menu_style': 'Estilo do Menu Móvel',
    'theme_editor_mobile_menu_overlay': 'Sobreposição de Tela Cheia',
    'theme_editor_mobile_menu_sidepanel': 'Painel Lateral',
    'theme_editor_mobile_menu_bg': 'Fundo do Menu',
    'theme_editor_mobile_menu_text': 'Texto do Menu',
    'theme_editor_mobile_menu_accent': 'Destaque/Hover do Menu',
    'theme_editor_global_colors': 'Cores Globais',
    'theme_editor_bg_color': 'Cor de Fundo',
    'theme_editor_accent_color': 'Cor de Destaque/Marca',
    'theme_editor_text_primary_color': 'Cor do Texto Principal',
    'theme_editor_text_secondary_color': 'Cor do Texto Secundário',
    'theme_editor_btn_bg_color': 'Fundo do Botão',
    'theme_editor_btn_text_color': 'Texto do Botão',
    'theme_editor_surface_color': 'Cor de Superfície (Cartões)',
    'theme_editor_border_color': 'Cor da Borda',
    'theme_editor_typography': 'Tipografia',
    'theme_editor_font_family': 'Família da Fonte',
    'theme_editor_font_weight': 'Peso da Fonte',
    'theme_editor_transform': 'Transformação',
    'theme_editor_discard': 'Descartar Alterações',
    'font_weight_light': 'Leve',
    'font_weight_normal': 'Normal',
    'font_weight_medium': 'Médio',
    'font_weight_semibold': 'Seminegrito',
    'font_weight_bold': 'Negrito',
    'font_weight_extrabold': 'Extranegrito',

    // Button Style Editor
    'button_editor_title': 'Editar Estilo do Botão',
    'button_editor_presets': 'Predefinições',
    'button_editor_preset_solid': 'Sólido',
    'button_editor_preset_outline': 'Contorno',
    'button_editor_preset_ghost': 'Transparente',
    'button_editor_preset_glass': 'Vidro',
    'button_editor_preset_gradient': 'Gradiente',
    'button_editor_colors': 'Cores & Preenchimento',
    'button_editor_gradient': 'Cores do Gradiente',
    'button_editor_background': 'Fundo',
    'button_editor_text': 'Texto',
    'button_editor_border_shape': 'Borda & Forma',
    'button_editor_border_color': 'Cor da Borda',
    'button_editor_border_width': 'Largura da Borda',
    'button_editor_corner_radius': 'Raio do Canto',
    'button_editor_shadow': 'Sombra',
    'button_editor_typography_spacing': 'Tipografia & Espaçamento',
    'button_editor_padding': 'Espaçamento Interno',
    'button_editor_preview': 'Pré-visualização',
    'button_editor_preview_text': 'Texto do Botão',
    'button_editor_apply_all_confirm': 'Aplicar este estilo a todos os botões similares? Esta ação não pode ser desfeita.',
    'button_editor_apply_all_buy_now': "Aplicar a todos os botões 'Comprar Agora'",
    
    // Card Style Editor
    'card_editor_title': 'Editar Estilo do Cartão',
    'card_editor_fill_stroke': 'Preenchimento & Contorno',
    'card_editor_background': 'Fundo',
    'card_editor_border': 'Borda',
    'card_editor_shape_shadow': 'Forma & Sombra',
    'card_editor_border_width': 'Largura da Borda',
    'card_editor_corner_radius': 'Raio do Canto',
    'card_editor_shadow': 'Sombra',
    'card_editor_preview': 'Pré-visualização',
    'card_editor_preview_text': 'Cartão',
    
    // Pages Tab
    'admin_page_saved_success': 'Página salva!',
    'admin_page_static_delete_error': 'Páginas estáticas não podem ser excluídas.',
    'admin_page_static_tag': '(Estática)',
    'admin_page_nav_visible': 'Visível na navegação',
    'admin_page_nav_hidden': 'Oculto da navegação',
    'admin_container_features': 'Recursos',
    'admin_container_feature_title_placeholder': 'Título do Recurso',
    'admin_container_feature_desc_placeholder': 'Descrição do Recurso',
    'admin_container_select_icon': 'Selecionar Ícone',
    'admin_container_add_feature': 'Adicionar Recurso',
    'admin_container_video_url': 'URL do Vídeo (YouTube/Vimeo)',
    'admin_container_type_not_editable': 'Tipo de contêiner não possui campos editáveis.',
    'admin_container_palette_title': 'Paleta de Conteúdo',
    'admin_container_palette_drag_title': 'Arraste para adicionar {label}',

    // Settings Tab
    'admin_settings_saved_success': 'Configurações salvas!',
    'admin_settings_icon_picker_title': 'Selecionar Ícone Social',
    'admin_settings_icon_picker_search': 'Buscar ícones...',
    'admin_settings_icon_picker_select': 'Selecionar Ícone',
    'admin_settings_icon_picker_none_found': 'Nenhum ícone encontrado.',
    'admin_settings_discard': 'Descartar',

    // AI Settings Tab
    'admin_ai_settings_saved_success': 'Configurações de IA salvas!',
    'admin_ai_settings_robot_1': 'Robô 1',
    'admin_ai_settings_robot_2': 'Robô 2',
    
    // Integrations Tab
    'admin_integrations_saved_success': 'Configurações de integração salvas!',

    // AI Components
    'ai_error_generating': 'Ocorreu um erro ao gerar o conteúdo. Por favor, verifique o console.',
    
    // Document Viewer
    'doc_viewer_download_error': 'Não foi possível baixar a imagem. Por favor, tente novamente.',

  },
  en: {
    joinNow: 'Join Now',
    buyNow: 'Buy Now',
    contact_form_title: 'Get in Touch',
    contact_form_name: 'Your Name',
    contact_form_email: 'Your Email',
    contact_form_message: 'Your Message',
    contact_form_submit: 'Send Message',
    contact_form_success: 'Thank you for your message! We will get back to you shortly.',
    'contact_form_sending': 'Sending...',
    'contact_form_alert_demo': 'In a real application, this would send an email or save the data to a server.',
    chatbot_greeting: 'Hello! 👋 I\'m {chatbotName}. How can I help you today?',
    chatbot_placeholder: 'Type your question...',
    admin_dashboard: 'Home',
    admin_pages: 'Pages',
    admin_store: 'Store',
    admin_offers: 'Offers',
    admin_carts: 'Carts',
    admin_orders: 'Orders',
    admin_advertising: 'Advertising',
    admin_downloads: 'Downloads',
    admin_theme: 'Theme',
    admin_settings: 'Site Settings',
    admin_ai_settings: 'AI Settings',
    admin_integrations: 'Integrations',
    admin_welcome: 'Welcome to the Admin Panel',
    admin_welcome_desc: 'Use the navigation on the left to manage your site\'s content.',
    admin_downloads_title: 'Downloads Management',
    admin_downloads_plan: 'Marketing Plan Pages',
    admin_downloads_catalog: 'Product Catalog Pages',
    admin_downloads_add_page: 'Add Page',
    admin_pages_title: 'Page Builder',
    admin_pages_desc: 'Create and manage the content of your website pages.',
    admin_pages_add: 'Create New Page',
    admin_pages_create_title: 'Create New Page',
    'admin_page_editor_title': 'Page Editor',
    'admin_page_meta_title': 'Page Settings',
    'admin_page_seo_title': 'SEO Settings',
    'admin_page_field_title': 'Page Title',
    'admin_page_field_slug': 'URL Slug (e.g., about-us)',
    'admin_page_field_nav': 'Show in Main Navigation',
    'admin_page_field_product': 'Associated Product (Optional)',
    'admin_page_field_product_none': 'None',
    'admin_page_field_meta_title': 'Meta Title',
    'admin_page_field_meta_desc': 'Meta Description',
    'admin_page_containers_title': 'Content Containers',
    'admin_page_containers_add': 'Add Container',
    'admin_container_select_type': 'Select container type',
    'admin_container_type_text': 'Text',
    'admin_container_type_image': 'Image',
    'admin_container_type_textImage': 'Text + Image',
    'admin_container_type_columns': 'Columns',
    'admin_container_type_contactForm': 'Contact Form',
    'admin_container_type_video': 'Video',
    'admin_container_type_hero': 'Hero Section',
    'admin_container_type_about': 'About Section',
    'admin_container_type_differentiators': 'Differentiators Section',
    'admin_container_type_productsCarousel': 'Products Carousel',
    'admin_container_type_promotionsCarousel': 'Promotions Carousel',
    'admin_container_type_teamMembers': 'Team Members',
    'admin_container_type_downloadsList': 'Downloads List',
    'admin_container_type_advertisingList': 'Advertising List',
    'admin_container_edit_title': 'Edit Container',
    'admin_container_field_title': 'Title (Optional)',
    'admin_container_field_subtitle': 'Subtitle (Optional)',
    'admin_container_field_content': 'Text Content',
    'admin_container_field_img_url': 'Image URL',
    'admin_container_field_alt': 'Image Alt Text',
    'admin_container_field_layout': 'Layout',
    'admin_layout_img_left': 'Image Left',
    'admin_layout_img_right': 'Image Right',
    'admin_layout_img_top': 'Image Top',
    'admin_layout_img_bottom': 'Image Bottom',
    admin_advertising_title: 'Advertisement Manager',
    admin_advertising_desc: 'Create and manage the advertisements and campaigns that appear on the site.',
    admin_advertising_add: 'Create New Ad',
    admin_ad_editor_title: 'Ad Editor',
    admin_ad_field_title: 'Ad Title',
    admin_ad_field_desc: 'Description',
    'admin_ad_field_img_url': 'Ad Image URL',
    'admin_ad_field_cta_text': 'Button Text (CTA)',
    'admin_ad_field_cta_link': 'Button Link (CTA)',
    'admin_ad_field_active': 'Ad Active',
    admin_button_cancel: 'Cancel',
    admin_button_create: 'Create',
    admin_button_save: 'Save Changes',
    'admin_button_save_short': 'Save',
    admin_button_delete: 'Delete',
    admin_product_editor_title: 'Product Editor',
    admin_product_add_digital: '+ Add Digital',
    admin_product_add_physical: '+ Add Physical',
    'admin_store_management_title': 'Store Management',
    'admin_store_management_desc': 'Add, edit, and manage your store\'s products.',
    admin_product_digital_products_title: 'Digital Products',
    admin_product_physical_products_title: 'Physical Products',
    admin_product_field_name: 'Name',
    admin_product_field_category: 'Category',
    admin_product_field_description: 'Description',
    admin_product_field_price: 'Price (BRL)',
    'admin_product_field_purchase_url': 'Purchase URL',
    'admin_product_tab_general': 'General',
    'admin_product_tab_images': 'Images',
    'admin_product_tab_variants': 'Variants',
    'admin_product_tab_reviews': 'Reviews',
    admin_ai_title: 'Artificial Intelligence Settings',
    admin_ai_desc: 'Manage the behavior and appearance of your AI assistant.',
    admin_chatbot_config_title: 'Chatbot Configuration',
    admin_chatbot_name: 'Chatbot Name',
    admin_chatbot_icon: 'Chatbot Icon',
    admin_chatbot_prompt: 'Chatbot System Prompt (Instructions)',
    admin_chatbot_prompt_desc: 'Instructions for the AI on how to behave, its tone, and the information it should know.',
    admin_integrations_title: 'API Integrations',
    admin_integrations_desc: 'Configure API keys for third-party services.',
    admin_payment_gateways: 'Payment Gateways',
    admin_shipping_integrations: 'Shipping Integrations',
    admin_key_mercado_pago: 'Mercado Pago Key',
    admin_key_adyen: 'Adyen Key',
    admin_key_stripe: 'Stripe Key',
    admin_key_pagseguro: 'PagSeguro Key',
    admin_key_stone: 'Stone Key',
    admin_key_asaas: 'Asaas Key',
    admin_key_melhor_envio: 'Melhor Envio Key',
    admin_api_keys_note_title: 'Important Note on API Keys',
    admin_api_keys_note_desc: 'For your security, the Gemini API key (the brain of our chatbot) is managed in a secure server environment (environment variables) and cannot be edited here. The keys below are for payment integrations and are saved locally in your browser.',
    admin_settings_social_title: 'Social Media Links',
    admin_settings_social_desc: 'Add, edit, or remove the social media links that appear in the site footer.',
    admin_settings_social_add: 'Add New Link',
    admin_settings_social_platform: 'Platform (e.g., facebook, x)',
    admin_settings_social_url: 'Link URL',
    advertising_no_ads: 'No active advertisements at the moment.',
    'admin_banners_tab_label': 'Banners',
    'admin_banners_title': 'Banner Management',
    'admin_banners_side_banner': 'Side Banner',
    'admin_banners_background_banner': 'Background Banner',
    'admin_banners_disabled_enabled': 'Disabled / Enabled',
    'admin_banners_image_url': 'Image URL',
    'admin_banners_link_url': 'Link URL',
    'admin_banners_position': 'Position',
    'admin_banners_position_left': 'Left',
    'admin_banners_position_right': 'Right',
    'admin_banners_top_offset': 'Top Offset',
    'admin_banners_width': 'Width',
    'admin_banners_opacity': 'Image Opacity',
    'admin_banners_opacity_hint': '(makes it clearer or darker)',
    'admin_banners_save': 'Save Banner Settings',
    'admin_panel_minimize': 'Minimize',
    'admin_panel_maximize': 'Maximize',
    'admin_panel_restore': 'Restore',
    'admin_panel_close': 'Close Panel',
    'admin_panel_view_site': 'View Site',
    'admin_panel_logout': 'Logout',
    'admin_login_title': 'Administrator Login',
    'admin_login_email': 'Email',
    'admin_login_password': 'Password',
    'admin_login_remember': 'Remember Me',
    'admin_login_error': 'Invalid email or password.',
    'admin_login_button': 'Login',
    'admin_login_close_aria': 'Close login panel',
    'theme_editor_title': 'Theme Customization',
    'theme_editor_reset': 'Reset to Default',
    'theme_editor_reset_confirm': 'Are you sure you want to reset all theme settings to default? Your changes will be lost unless you save them.',
    'theme_editor_saved_success': 'Theme saved successfully!',
    'theme_editor_header_nav': 'Header & Navigation',
    'theme_editor_mobile_menu_style': 'Mobile Menu Style',
    'theme_editor_mobile_menu_overlay': 'Full Screen Overlay',
    'theme_editor_mobile_menu_sidepanel': 'Side Panel',
    'theme_editor_mobile_menu_bg': 'Menu Background',
    'theme_editor_mobile_menu_text': 'Menu Text',
    'theme_editor_mobile_menu_accent': 'Menu Accent/Hover',
    'theme_editor_global_colors': 'Global Colors',
    'theme_editor_bg_color': 'Background Color',
    'theme_editor_accent_color': 'Accent/Brand Color',
    'theme_editor_text_primary_color': 'Primary Text Color',
    'theme_editor_text_secondary_color': 'Secondary Text Color',
    'theme_editor_btn_bg_color': 'Button Background',
    'theme_editor_btn_text_color': 'Button Text',
    'theme_editor_surface_color': 'Surface Color (Cards)',
    'theme_editor_border_color': 'Border Color',
    'theme_editor_typography': 'Typography',
    'theme_editor_font_family': 'Font Family',
    'theme_editor_font_weight': 'Font Weight',
    'theme_editor_transform': 'Transform',
    'theme_editor_discard': 'Discard Changes',
    'font_weight_light': 'Light',
    'font_weight_normal': 'Normal',
    'font_weight_medium': 'Medium',
    'font_weight_semibold': 'Semi-Bold',
    'font_weight_bold': 'Bold',
    'font_weight_extrabold': 'Extra-Bold',
    'button_editor_title': 'Edit Button Style',
    'button_editor_presets': 'Presets',
    'button_editor_preset_solid': 'Solid',
    'button_editor_preset_outline': 'Outline',
    'button_editor_preset_ghost': 'Ghost',
    'button_editor_preset_glass': 'Glass',
    'button_editor_preset_gradient': 'Gradient',
    'button_editor_colors': 'Colors & Fill',
    'button_editor_gradient': 'Gradient Colors',
    'button_editor_background': 'Background',
    'button_editor_text': 'Text',
    'button_editor_border_shape': 'Border & Shape',
    'button_editor_border_color': 'Border Color',
    'button_editor_border_width': 'Border Width',
    'button_editor_corner_radius': 'Corner Radius',
    'button_editor_shadow': 'Shadow',
    'button_editor_typography_spacing': 'Typography & Spacing',
    'button_editor_padding': 'Padding',
    'button_editor_preview': 'Live Preview',
    'button_editor_preview_text': 'Button Text',
    'button_editor_apply_all_confirm': 'Apply this style to all similar buttons? This cannot be undone.',
    'button_editor_apply_all_buy_now': "Apply to all 'Buy Now' buttons",
    'card_editor_title': 'Edit Card Style',
    'card_editor_fill_stroke': 'Fill & Stroke',
    'card_editor_background': 'Background',
    'card_editor_border': 'Border',
    'card_editor_shape_shadow': 'Shape & Shadow',
    'card_editor_border_width': 'Border Width',
    'card_editor_corner_radius': 'Corner Radius',
    'card_editor_shadow': 'Shadow',
    'card_editor_preview': 'Live Preview',
    'card_editor_preview_text': 'Card',
    'admin_page_saved_success': 'Page saved!',
    'admin_page_static_delete_error': 'Static pages cannot be deleted.',
    'admin_page_static_tag': '(Static)',
    'admin_page_nav_visible': 'Visible in navigation',
    'admin_page_nav_hidden': 'Hidden from navigation',
    'admin_container_features': 'Features',
    'admin_container_feature_title_placeholder': 'Feature Title',
    'admin_container_feature_desc_placeholder': 'Feature Description',
    'admin_container_select_icon': 'Select Icon',
    'admin_container_add_feature': 'Add Feature',
    'admin_container_video_url': 'Video URL (YouTube/Vimeo)',
    'admin_container_type_not_editable': 'Container type has no editable fields.',
    'admin_container_palette_title': 'Content Palette',
    'admin_container_palette_drag_title': 'Drag to add {label}',
    'admin_settings_saved_success': 'Settings saved!',
    'admin_settings_icon_picker_title': 'Select Social Icon',
    'admin_settings_icon_picker_search': 'Search icons...',
    'admin_settings_icon_picker_select': 'Select Icon',
    'admin_settings_icon_picker_none_found': 'No icons found.',
    'admin_settings_discard': 'Discard',
    'admin_ai_settings_saved_success': 'AI settings saved!',
    'admin_ai_settings_robot_1': 'Robot 1',
    'admin_ai_settings_robot_2': 'Robot 2',
    'admin_integrations_saved_success': 'Integration settings saved!',
    'ai_error_generating': 'An error occurred while generating content. Please check the console.',
    'doc_viewer_download_error': 'Could not download the image. Please try again.',
  },
  es: {
    joinNow: 'Únete Ahora',
    buyNow: 'Comprar Ahora',
    contact_form_title: 'Ponerse en Contacto',
    contact_form_name: 'Tu Nombre',
    contact_form_email: 'Tu Correo Electrónico',
    contact_form_message: 'Tu Mensaje',
    contact_form_submit: 'Enviar Mensaje',
    contact_form_success: '¡Gracias por tu mensaje! Nos pondremos en contacto contigo en breve.',
    'contact_form_sending': 'Enviando...',
    'contact_form_alert_demo': 'En una aplicación real, esto enviaría un correo electrónico o guardaría los datos en un servidor.',
    chatbot_greeting: '¡Hola! 👋 Soy {chatbotName}. ¿Cómo puedo ayudarte hoy?',
    chatbot_placeholder: 'Escribe tu pregunta...',
    admin_dashboard: 'Inicio',
    admin_pages: 'Páginas',
    admin_store: 'Tienda',
    admin_offers: 'Ofertas',
    admin_carts: 'Carritos',
    admin_orders: 'Pedidos',
    admin_advertising: 'Anuncios',
    admin_downloads: 'Descargas',
    admin_theme: 'Tema',
    admin_settings: 'Configuración del Sitio',
    admin_ai_settings: 'Configuración de IA',
    admin_integrations: 'Integraciones',
    admin_welcome: 'Bienvenido al Panel de Administración',
    admin_welcome_desc: 'Usa la navegación a la izquierda para gestionar el contenido de tu sitio.',
    admin_downloads_title: 'Gestión de Descargas',
    admin_downloads_plan: 'Páginas del Plan de Marketing',
    admin_downloads_catalog: 'Páginas del Catálogo de Productos',
    admin_downloads_add_page: 'Añadir Página',
    admin_pages_title: 'Constructor de Páginas',
    admin_pages_desc: 'Crea y gestiona el contenido de las páginas de tu sitio web.',
    admin_pages_add: 'Crear Nueva Página',
    admin_pages_create_title: 'Crear Nueva Página',
    'admin_page_editor_title': 'Editor de Página',
    'admin_page_meta_title': 'Configuración de Página',
    'admin_page_seo_title': 'Configuración de SEO',
    'admin_page_field_title': 'Título de la Página',
    'admin_page_field_slug': 'URL Slug (ej: sobre-nosotros)',
    'admin_page_field_nav': 'Mostrar en Navegación Principal',
    'admin_page_field_product': 'Producto Asociado (Opcional)',
    'admin_page_field_product_none': 'Ninguno',
    'admin_page_containers_title': 'Contenedores de Contenido',
    'admin_page_containers_add': 'Añadir Contenedor',
    'admin_container_select_type': 'Selecciona el tipo de contenedor',
    'admin_container_type_text': 'Texto',
    'admin_container_type_image': 'Imagen',
    'admin_container_type_textImage': 'Texto + Imagen',
    'admin_container_type_columns': 'Columnas',
    'admin_container_type_contactForm': 'Formulario de Contacto',
    'admin_container_type_video': 'Video',
    'admin_container_type_hero': 'Sección Hero',
    'admin_container_type_about': 'Seção Sobre',
    'admin_container_type_differentiators': 'Seção Diferenciais',
    'admin_container_type_productsCarousel': 'Carrossel de Produtos',
    'admin_container_type_promotionsCarousel': 'Carrossel de Promoções',
    'admin_container_type_teamMembers': 'Membros da Equipe',
    'admin_container_type_downloadsList': 'Lista de Descargas',
    'admin_container_type_advertisingList': 'Lista de Anuncios',
    'admin_container_edit_title': 'Editar Contenedor',
    'admin_container_field_title': 'Título (Opcional)',
    'admin_container_field_subtitle': 'Subtítulo (Opcional)',
    'admin_container_field_content': 'Contenido de Texto',
    'admin_container_field_img_url': 'URL de la Imagen',
    'admin_container_field_alt': 'Texto Alternativo de la Imagen',
    'admin_container_field_layout': 'Diseño',
    'admin_layout_img_left': 'Imagen a la Izquierda',
    'admin_layout_img_right': 'Imagen a la Derecha',
    'admin_layout_img_top': 'Imagen Arriba',
    'admin_layout_img_bottom': 'Imagen Abajo',
    admin_advertising_title: 'Gestor de Anuncios',
    admin_advertising_desc: 'Crea y gestiona los anuncios y campañas que aparecen en el sitio.',
    admin_advertising_add: 'Crear Nuevo Anuncio',
    admin_ad_editor_title: 'Editor de Anuncios',
    admin_ad_field_title: 'Título del Anuncio',
    admin_ad_field_desc: 'Descripción',
    'admin_ad_field_img_url': 'URL de la Imagen del Anuncio',
    'admin_ad_field_cta_text': 'Texto del Botón (CTA)',
    'admin_ad_field_cta_link': 'Enlace del Botón (CTA)',
    'admin_ad_field_active': 'Anuncio Activo',
    admin_button_cancel: 'Cancelar',
    admin_button_create: 'Crear',
    admin_button_save: 'Guardar Cambios',
    'admin_button_save_short': 'Guardar',
    admin_button_delete: 'Eliminar',
    admin_product_editor_title: 'Editor de Productos',
    admin_product_add_digital: '+ Añadir Digital',
    admin_product_add_physical: '+ Añadir Físico',
    'admin_store_management_title': 'Gestión de la Tienda',
    'admin_store_management_desc': 'Añade, edita y gestiona los productos de tu tienda.',
    admin_product_digital_products_title: 'Productos Digitales',
    admin_product_physical_products_title: 'Productos Físicos',
    admin_product_field_name: 'Nombre',
    admin_product_field_category: 'Categoría',
    admin_product_field_description: 'Descripción',
    admin_product_field_price: 'Precio (BRL)',
    'admin_product_field_purchase_url': 'URL de Compra',
    'admin_product_tab_general': 'General',
    'admin_product_tab_images': 'Imágenes',
    'admin_product_tab_variants': 'Variaciones',
    'admin_product_tab_reviews': 'Reseñas',
    admin_ai_title: 'Configuración de Inteligencia Artificial',
    admin_ai_desc: 'Gestiona el comportamiento y la apariencia de tu asistente de IA.',
    admin_chatbot_config_title: 'Configuración del Chatbot',
    admin_chatbot_name: 'Nombre del Chatbot',
    admin_chatbot_icon: 'Icono del Chatbot',
    admin_chatbot_prompt: 'Prompt del Sistema del Chatbot (Instrucciones)',
    admin_chatbot_prompt_desc: 'Instrucciones para la IA sobre cómo comportarse, su tono y la información que debe conocer.',
    admin_integrations_title: 'Integraciones de API',
    admin_integrations_desc: 'Configura claves de API para servicios de terceros.',
    admin_payment_gateways: 'Pasarelas de Pago',
    admin_shipping_integrations: 'Integraciones de Envío',
    admin_key_mercado_pago: 'Clave de Mercado Pago',
    admin_key_adyen: 'Clave de Adyen',
    admin_key_stripe: 'Clave de Stripe',
    admin_key_pagseguro: 'Clave de PagSeguro',
    admin_key_stone: 'Clave de Stone',
    admin_key_asaas: 'Clave de Asaas',
    admin_key_melhor_envio: 'Clave de Melhor Envio',
    admin_api_keys_note_title: 'Nota Importante Sobre las Claves de API',
    admin_api_keys_note_desc: 'Por su seguridad, la clave de API de Gemini (el cerebro de nuestro chatbot) se gestiona en un entorno seguro del servidor (variables de entorno) y no se puede editar aquí. Las claves a continuación son para integraciones de pago y se guardan localmente en su navegador.',
    admin_settings_social_title: 'Enlaces de Redes Sociales',
    admin_settings_social_desc: 'Añada, edite o elimine los enlaces de redes sociales que aparecen en el pie de página del sitio.',
    admin_settings_social_add: 'Añadir Nuevo Enlace',
    admin_settings_social_platform: 'Plataforma (ej: facebook, x)',
    admin_settings_social_url: 'URL del Enlace',
    advertising_no_ads: 'No hay anuncios activos en este momento.',
    'admin_banners_tab_label': 'Banners',
    'admin_banners_title': 'Gestión de Banners',
    'admin_banners_side_banner': 'Banner Lateral',
    'admin_banners_background_banner': 'Banner de Fondo',
    'admin_banners_disabled_enabled': 'Desactivado / Activado',
    'admin_banners_image_url': 'URL de la Imagen',
    'admin_banners_link_url': 'URL del Enlace',
    'admin_banners_position': 'Posición',
    'admin_banners_position_left': 'Izquierda',
    'admin_banners_position_right': 'Derecha',
    'admin_banners_top_offset': 'Distancia Superior',
    'admin_banners_width': 'Ancho',
    'admin_banners_opacity': 'Opacidad de la Imagen',
    'admin_banners_opacity_hint': '(la hace más clara u oscura)',
    'admin_banners_save': 'Guardar Configuración de Banners',
    'admin_panel_minimize': 'Minimizar',
    'admin_panel_maximize': 'Maximizar',
    'admin_panel_restore': 'Restaurar',
    'admin_panel_close': 'Cerrar Panel',
    'admin_panel_view_site': 'Ver Sitio',
    'admin_panel_logout': 'Cerrar Sesión',
    'admin_login_title': 'Inicio de Sesión de Administrador',
    'admin_login_email': 'Correo Electrónico',
    'admin_login_password': 'Contraseña',
    'admin_login_remember': 'Recordarme',
    'admin_login_error': 'Correo electrónico o contraseña no válidos.',
    'admin_login_button': 'Iniciar Sesión',
    'admin_login_close_aria': 'Cerrar panel de inicio de sesión',
    'theme_editor_title': 'Personalización del Tema',
    'theme_editor_reset': 'Restablecer a Predeterminado',
    'theme_editor_reset_confirm': '¿Estás seguro de que quieres restablecer toda la configuración del tema a los valores predeterminados? Tus cambios se perderán a menos que los guardes.',
    'theme_editor_saved_success': '¡Tema guardado con éxito!',
    'theme_editor_header_nav': 'Encabezado y Navegación',
    'theme_editor_mobile_menu_style': 'Estilo de Menú Móvil',
    'theme_editor_mobile_menu_overlay': 'Superposición de Pantalla Completa',
    'theme_editor_mobile_menu_sidepanel': 'Panel Lateral',
    'theme_editor_mobile_menu_bg': 'Fondo del Menú',
    'theme_editor_mobile_menu_text': 'Texto del Menú',
    'theme_editor_mobile_menu_accent': 'Acento/Hover del Menú',
    'theme_editor_global_colors': 'Colores Globales',
    'theme_editor_bg_color': 'Color de Fondo',
    'theme_editor_accent_color': 'Color de Acento/Marca',
    'theme_editor_text_primary_color': 'Color de Texto Principal',
    'theme_editor_text_secondary_color': 'Color de Texto Secundario',
    'theme_editor_btn_bg_color': 'Fondo del Botón',
    'theme_editor_btn_text_color': 'Texto del Botón',
    'theme_editor_surface_color': 'Color de Superficie (Tarjetas)',
    'theme_editor_border_color': 'Color del Borde',
    'theme_editor_typography': 'Tipografía',
    'theme_editor_font_family': 'Familia de Fuentes',
    'theme_editor_font_weight': 'Peso de la Fuente',
    'theme_editor_transform': 'Transformación',
    'theme_editor_discard': 'Descartar Cambios',
    'font_weight_light': 'Ligero',
    'font_weight_normal': 'Normal',
    'font_weight_medium': 'Medio',
    'font_weight_semibold': 'Seminegrita',
    'font_weight_bold': 'Negrita',
    'font_weight_extrabold': 'Extranegrita',
    'button_editor_title': 'Editar Estilo de Botón',
    'button_editor_presets': 'Preajustes',
    'button_editor_preset_solid': 'Sólido',
    'button_editor_preset_outline': 'Contorno',
    'button_editor_preset_ghost': 'Fantasma',
    'button_editor_preset_glass': 'Cristal',
    'button_editor_preset_gradient': 'Gradiente',
    'button_editor_colors': 'Colores y Relleno',
    'button_editor_gradient': 'Colores de Gradiente',
    'button_editor_background': 'Fondo',
    'button_editor_text': 'Texto',
    'button_editor_border_shape': 'Borde y Forma',
    'button_editor_border_color': 'Color del Borde',
    'button_editor_border_width': 'Ancho del Borde',
    'button_editor_corner_radius': 'Radio de Esquina',
    'button_editor_shadow': 'Sombra',
    'button_editor_typography_spacing': 'Tipografía y Espaciado',
    'button_editor_padding': 'Relleno',
    'button_editor_preview': 'Vista Previa',
    'button_editor_preview_text': 'Texto del Botón',
    'button_editor_apply_all_confirm': '¿Aplicar este estilo a todos los botones similares? Esta acción no se puede deshacer.',
    'button_editor_apply_all_buy_now': "Aplicar a todos los botones 'Comprar Ahora'",
    'card_editor_title': 'Editar Estilo de Tarjeta',
    'card_editor_fill_stroke': 'Relleno y Borde',
    'card_editor_background': 'Fondo',
    'card_editor_border': 'Borde',
    'card_editor_shape_shadow': 'Forma y Sombra',
    'card_editor_border_width': 'Ancho del Borde',
    'card_editor_corner_radius': 'Radio de Esquina',
    'card_editor_shadow': 'Sombra',
    'card_editor_preview': 'Vista Previa',
    'card_editor_preview_text': 'Tarjeta',
    'admin_page_saved_success': '¡Página guardada!',
    'admin_page_static_delete_error': 'Las páginas estáticas no se pueden eliminar.',
    'admin_page_static_tag': '(Estática)',
    'admin_page_nav_visible': 'Visible en la navegación',
    'admin_page_nav_hidden': 'Oculto de la navegación',
    'admin_container_features': 'Características',
    'admin_container_feature_title_placeholder': 'Título de la Característica',
    'admin_container_feature_desc_placeholder': 'Descripción de la Característica',
    'admin_container_select_icon': 'Seleccionar Icono',
    'admin_container_add_feature': 'Añadir Característica',
    'admin_container_video_url': 'URL del Video (YouTube/Vimeo)',
    'admin_container_type_not_editable': 'El tipo de contenedor no tiene campos editables.',
    'admin_container_palette_title': 'Paleta de Contenido',
    'admin_container_palette_drag_title': 'Arrastrar para añadir {label}',
    'admin_settings_saved_success': '¡Configuración guardada!',
    'admin_settings_icon_picker_title': 'Seleccionar Icono Social',
    'admin_settings_icon_picker_search': 'Buscar iconos...',
    'admin_settings_icon_picker_select': 'Seleccionar Icono',
    'admin_settings_icon_picker_none_found': 'No se encontraron iconos.',
    'admin_settings_discard': 'Descartar',
    'admin_ai_settings_saved_success': '¡Configuración de IA guardada!',
    'admin_ai_settings_robot_1': 'Robot 1',
    'admin_ai_settings_robot_2': 'Robot 2',
    'admin_integrations_saved_success': '¡Configuración de integración guardada!',
    'ai_error_generating': 'Ocurrió un error al generar contenido. Por favor, revisa la consola.',
    'doc_viewer_download_error': 'No se pudo descargar la imagen. Por favor, inténtalo de nuevo.',
  },
};